export const actionTypes = {
  FETCH_POSTS: "FETCH_POSTS",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  LIKE_POST: "LIKE_POST",
  DELETE_POST: "DELETE_POST",
  ERROR: "ERROR",
  ISLOADING: "LOADING",
  POSt_LOADING: "POSt_LOADING",
  POSt_ERROR: "POSt_ERROR",
};
